name: Concurrency Parent

# TODO maybe enable this when testing
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo matrix=$(python nek.py) >> $GITHUB_OUTPUT
  call-workflow-2-in-local-repo:
    needs: job1
    uses: ./.github/workflows/concurrency_test_child.yml

