name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'commit to run tests against'
        required: true
        type: string
      ci_job_url:
        description: 'parent job url'
        type: string
      ci_job_id:
        description: 'parent job id'
        type: number




jobs:
  print-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run:
          - echo "neki 1" ${{ github.event.inputs.commit }}
          - echo "JOB ID" ${{ github.event.inputs.ci_job_id }}
          - echo "JOB URL" ${{ github.event.inputs.ci_job_url }}

