name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      custom_connection_id:
        description: 'needed for status return to custom connection'
        required: true
        type: string
      commit:
        description: 'commit to run tests against'
        required: true
        type: string
      ci_job_url:
        description: 'parent job url'
        type: string
      ci_job_id:
        description: 'parent job id'
        type: number

jobs:
  print-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: custom_connection_id_${{ github.event.inputs.custom_connection_id }}
        run: |
          echo custom_connection_id_${{ github.event.inputs.custom_connection_id }}
          echo "neki 1" ${{ github.event.inputs.commit }}
          echo "JOB ID" ${{ github.event.inputs.ci_job_id }}
          echo "JOB URL" ${{ github.event.inputs.ci_job_url }}

  print-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: test-2
        run: echo test 2

  print-test-3:
    runs-on: ubuntu-latest
    needs: [print-test-2]
    steps:
      - name: test-3
        run: echo test 3

