name: Test Workflow

on: push

jobs:

  print-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "neki 1"

  print-test-1-5:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "neki 1.5"

  print-test-2:
    needs: [print-test-1, print-test-1-5]
    if: '!cancelled()'
    runs-on: ubuntu-latest
    steps:
      - name: Echo something 2
        run: echo "neki 2"

