name: Test Workflow

on: push

jobs:

  print-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "neki 1"
        #run: exit 1

  print-test-1-5:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "neki 1.5"

  print-test-2:
    if: '!cancelled() && success()' # this runs if some jobs are skipped but not if one fails
    needs: [print-test-1, print-test-1-5]
    runs-on: ubuntu-latest
    steps:
      - name: Echo something 2
        run: echo "neki 2"

