name: Test Workflow

on: push

jobs:

  print-test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "neki 1"

  print-test-2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something 2
        run: echo "neki 2"

