name: Vars Test

on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: python nek.py >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - name: Something
        run: |
          export CONFIG_Debug=Nekajjj-conf
          echo ${{matrix.project}} ${{matrix.config}} $CONFIG_${{matrix.config}}

