name: Vars Test

on: push

jobs:
  some-calc-value:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: |
          echo matrix=[{"test": "something", "out": "neki"}, {"test": "something 2", "out": "neki 2"}] >> $GITHUB_OUTPUT
  second-step:
    runs-on: ubuntu-latest
    needs: [some-calc-value]
    strategy:
      matrix: ${{fromJson(needs.some_calc_value.outputs.matrix)}}
    steps:
    - name: Something
      run: |
        echo ${{matrix.camera}} ${{matrix.run}}

