name: Test Workflow

on: push

jobs:

  some_calc_value:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: |
          echo matrix=[{"test": "something", "out": "neki"}, {"test": "something 2", "out": "neki 2"}] >> $GITHUB_OUTPUT

  print-test-1:
    runs-on: ubuntu-latest
    needs: [some_calc_value]
    strategy:
      matrix: ${{fromJson(needs.some_calc_value.outputs.matrix)}}
    steps:
    - name: Something
      run: |
        echo ${{matrix.camera}} ${{matrix.run}}

