name: Test Workflow

on: push

jobs:

  some_calc_value:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: |
          echo "steps='[{\"name\": \"nek nek\", \"run\": \"echo neki iz din\"}]'" >> $GITHUB_OUTPUT

  print-test-1:
    runs-on: ubuntu-latest
    needs: [some_calc_value]
    steps: ${{fromJson(needs.some_calc_value.outputs.steps)}}

