name: Vars Test

on: push

jobs:
  some_calc_value:
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  second_step:
    runs-on: ubuntu-latest
    needs: [some_calc_value]
    strategy:
      matrix: ${{fromJson(needs.some_calc_value.outputs.matrix)}}
    steps:
    - name: Something
      run: |
        echo ${{matrix.camera}} ${{matrix.run}}

